#' Visualise the points and edges from \code{triangulate()}
#'
#' This function plots the points and edges from the
#' triangulate function to visualise the triangles
#' generated by connecting the five points
#'
#' @param plot_object output from the \code{triangulate()} function
#'
#' @returns A ggplot2 object
#' @importFrom tibble as_tibble
#' @import ggplot2
#' @import dplyr
#'
#' @export
#'
#' @examples
#' points <- matrix(c(0,0,1,1,2,0,3,1,4,0), nrow=5, byrow=TRUE)
#' results <- triangulate(points)
#' plot_triangles(results)
plot_triangles <- function(plot_object) {
  # Extract points and edges
  points <- plot_object$points
  edges <- plot_object$edges

  # Convert points and edges to a tibble for ggplot
  colnames(points) <- c('x','y')
  colnames(edges) <- c('from', 'to')
  points_df <- as_tibble(points)
  edges_df <- as_tibble(edges)

  # Add coordinates to edges_df
  x1_y1 <- points_df |>
    slice(edges_df$from) |>
    transmute(x1 = x, y1 = y)
  x2_y2 <- points_df |>
    slice(edges_df$to) |>
    transmute(x2 = x, y2 = y)
  edges_df <- edges_df |> dplyr::bind_cols(x1_y1, x2_y2)

  # Extend y and x axis limits to make some space around the plot.
  # We extend the limits 2 units above and below their range
  x_range <- range(points_df$x)
  y_range <- range(points_df$y)
  x_limits <- c(x_range[1] - 1.2, x_range[2] + 1.2)
  y_limits <- c(y_range[1] - 1.2, y_range[2] + 1.2)


  # Plot
  ggplot() +
    # plot the edges (connecting the points)
    geom_segment(
      data = edges_df,
      aes(x = x1, y = y1, xend = x2, yend = y2),
      colour = 'navy',
      linewidth = 0.7
    ) +
    # plot the points
    geom_point(
      data = points_df,
      aes(x = x, y = y),
      colour = 'black', size = 2.5
    ) +
    # Add labels to the points
    geom_label(
      data = points_df,
        aes(
          x = x, y = y,
          label = paste0('Point_',
                         rownames(points_df),
                         '(',round(x,1),',',round(y,1),')'),
        ), size = 2.5,
      vjust = -0.5, colour = 'black'
    ) +
    # Axis limits
    coord_cartesian(xlim = x_limits,
                    ylim = y_limits) +
    theme_void() + #removes all chart elements
    # Add title
    ggtitle('Triangulation of five points') +
    # Centre and bolden title
    theme(plot.title = element_text(hjust = 0.5, size = 13, face = 'bold'))
}



